"""execution latch survives a restart

Revision ID: f15a8f4765c1
Revises: fee924ff4c11
Create Date: 2026-10-01 16:39:00.233209
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'f15a8f4765c1'
down_revision = 'fee924ff4c11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.String(length=1024), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_by', sa.String(length=320), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_trips_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index('ix_execution_trips_open', ['account_id', 'cleared_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_trips_reason'), ['reason'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_trips_reason'))
        batch_op.drop_index('ix_execution_trips_open')
        batch_op.drop_index(batch_op.f('ix_execution_trips_occurred_at'))

    op.drop_table('execution_trips')
    # ### end Alembic commands ###
