"""initial schema

Revision ID: fee924ff4c11
Revises: 
Create Date: 2026-10-01 14:44:49.480106
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'fee924ff4c11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('broker', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('starting_equity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker', 'external_id', name='uq_account_broker_ext')
    )
    op.create_table('agent_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trade_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=48), nullable=False),
    sa.Column('conclusion', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('data_quality', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_analyses_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_analyses_produced_at'), ['produced_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_analyses_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_analyses_trade_id'), ['trade_id'], unique=False)

    op.create_table('ai_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trade_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('rejection_reasons', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_decisions_produced_at'), ['produced_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_decisions_trade_id'), ['trade_id'], unique=False)

    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('split', sa.String(length=16), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('cost_model', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtests_strategy'), ['strategy'], unique=False)

    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue', 'symbol', 'timeframe', 'opened_at', name='uq_candle')
    )
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.create_index('ix_candles_lookup', ['symbol', 'timeframe', 'opened_at'], unique=False)

    op.create_table('economic_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('impact', sa.String(length=8), nullable=False),
    sa.Column('currencies', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('actual', sa.String(length=64), nullable=True),
    sa.Column('forecast', sa.String(length=64), nullable=True),
    sa.Column('previous', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_event_source_id')
    )
    with op.batch_alter_table('economic_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_economic_events_impact'), ['impact'], unique=False)
        batch_op.create_index(batch_op.f('ix_economic_events_scheduled_for'), ['scheduled_for'], unique=False)

    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('asset_class', sa.String(length=24), nullable=False),
    sa.Column('base_currency', sa.String(length=16), nullable=True),
    sa.Column('quote_currency', sa.String(length=16), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('lot_step', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('contract_size', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('tick_value', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('pip_size', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('max_leverage', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('maker_fee_bps', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('taker_fee_bps', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('session', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue', 'symbol', name='uq_instrument_venue_symbol')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_symbol'), ['symbol'], unique=False)

    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('importance', sa.String(length=16), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'url', name='uq_news_source_url')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_items_published_at'), ['published_at'], unique=False)

    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('allowed_regimes', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('broker_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('credential_ref', sa.String(length=128), nullable=True),
    sa.Column('withdrawal_permission', sa.Boolean(), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('last_health_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_detail', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('average_fill_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('fees_paid', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('reject_reason', sa.String(length=512), nullable=True),
    sa.Column('risk_verdict', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_broker_order_id'), ['broker_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_client_order_id'), ['client_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_symbol'), ['symbol'], unique=False)

    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('scope_value', sa.String(length=64), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_metrics_captured_at'), ['captured_at'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('mark_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('realised_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fees_paid', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('protective_stop', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_symbol'), ['symbol'], unique=False)

    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.String(length=1024), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_events_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('risk_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('day_start_equity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('week_start_equity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('peak_equity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('realised_pnl_today', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('realised_pnl_week', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('trades_today', sa.Integer(), nullable=False),
    sa.Column('current_day', sa.String(length=10), nullable=False),
    sa.Column('week_start', sa.String(length=10), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('trading_paused', sa.Boolean(), nullable=False),
    sa.Column('daily_breaker_tripped', sa.Boolean(), nullable=False),
    sa.Column('weekly_breaker_tripped', sa.Boolean(), nullable=False),
    sa.Column('drawdown_breaker_tripped', sa.Boolean(), nullable=False),
    sa.Column('disabled_symbols', sa.JSON(), nullable=False),
    sa.Column('disabled_strategies', sa.JSON(), nullable=False),
    sa.Column('disabled_markets', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('considered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('planned_entry', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('planned_stop', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('planned_targets', sa.JSON(), nullable=False),
    sa.Column('planned_size', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('planned_risk', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('reward_risk', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('actual_entry', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('actual_exit', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('actual_size', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('fees', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('realised_pnl', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('r_multiple', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('mfe', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('mae', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('exit_reason', sa.String(length=64), nullable=True),
    sa.Column('regime', sa.String(length=24), nullable=True),
    sa.Column('session', sa.String(length=16), nullable=True),
    sa.Column('data_quality', sa.String(length=16), nullable=True),
    sa.Column('agent_outputs', sa.JSON(), nullable=False),
    sa.Column('ai_decision', sa.JSON(), nullable=False),
    sa.Column('risk_verdict', sa.JSON(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('market_structure', sa.JSON(), nullable=False),
    sa.Column('news_context', sa.JSON(), nullable=False),
    sa.Column('macro_context', sa.JSON(), nullable=False),
    sa.Column('order_ids', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_considered_at'), ['considered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_regime'), ['regime'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_session'), ['session'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_strategy'), ['strategy'], unique=False)
        batch_op.create_index('ix_trades_strategy_outcome', ['strategy', 'outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_trade_id'), ['trade_id'], unique=True)

    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_fill_id', sa.String(length=64), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fee', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('liquidity', sa.String(length=8), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_order_id'], ['orders.client_order_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_fill_id', name='uq_fill_venue_id')
    )
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fills_client_order_id'), ['client_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fills_client_order_id'))

    op.drop_table('fills')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_trade_id'))
        batch_op.drop_index(batch_op.f('ix_trades_symbol'))
        batch_op.drop_index('ix_trades_strategy_outcome')
        batch_op.drop_index(batch_op.f('ix_trades_strategy'))
        batch_op.drop_index(batch_op.f('ix_trades_session'))
        batch_op.drop_index(batch_op.f('ix_trades_regime'))
        batch_op.drop_index(batch_op.f('ix_trades_outcome'))
        batch_op.drop_index(batch_op.f('ix_trades_considered_at'))

    op.drop_table('trades')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    op.drop_table('risk_state')
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_risk_events_code'))

    op.drop_table('risk_events')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_symbol'))

    op.drop_table('positions')
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_metrics_captured_at'))

    op.drop_table('performance_metrics')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_symbol'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_client_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_broker_order_id'))

    op.drop_table('orders')
    op.drop_table('broker_connections')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('strategies')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_published_at'))

    op.drop_table('news_items')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_symbol'))

    op.drop_table('instruments')
    with op.batch_alter_table('economic_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_economic_events_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_economic_events_impact'))

    op.drop_table('economic_events')
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.drop_index('ix_candles_lookup')

    op.drop_table('candles')
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtests_strategy'))

    op.drop_table('backtests')
    with op.batch_alter_table('ai_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_decisions_trade_id'))
        batch_op.drop_index(batch_op.f('ix_ai_decisions_produced_at'))

    op.drop_table('ai_decisions')
    with op.batch_alter_table('agent_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_analyses_trade_id'))
        batch_op.drop_index(batch_op.f('ix_agent_analyses_symbol'))
        batch_op.drop_index(batch_op.f('ix_agent_analyses_produced_at'))
        batch_op.drop_index(batch_op.f('ix_agent_analyses_agent'))

    op.drop_table('agent_analyses')
    op.drop_table('accounts')
    # ### end Alembic commands ###
